// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	"time"

	"github.com/spf13/viper"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContainable creates a new instance of MockContainable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainable {
	mock := &MockContainable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContainable is an autogenerated mock type for the Containable type
type MockContainable struct {
	mock.Mock
}

type MockContainable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainable) EXPECT() *MockContainable_Expecter {
	return &MockContainable_Expecter{mock: &_m.Mock}
}

// AddObserver provides a mock function for the type MockContainable
func (_mock *MockContainable) AddObserver(o Observable) {
	_mock.Called(o)
	return
}

// MockContainable_AddObserver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddObserver'
type MockContainable_AddObserver_Call struct {
	*mock.Call
}

// AddObserver is a helper method to define mock.On call
//   - o Observable
func (_e *MockContainable_Expecter) AddObserver(o interface{}) *MockContainable_AddObserver_Call {
	return &MockContainable_AddObserver_Call{Call: _e.mock.On("AddObserver", o)}
}

func (_c *MockContainable_AddObserver_Call) Run(run func(o Observable)) *MockContainable_AddObserver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Observable
		if args[0] != nil {
			arg0 = args[0].(Observable)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_AddObserver_Call) Return() *MockContainable_AddObserver_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContainable_AddObserver_Call) RunAndReturn(run func(o Observable)) *MockContainable_AddObserver_Call {
	_c.Run(run)
	return _c
}

// AddObserverFunc provides a mock function for the type MockContainable
func (_mock *MockContainable) AddObserverFunc(f func(Containable, chan error)) {
	_mock.Called(f)
	return
}

// MockContainable_AddObserverFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddObserverFunc'
type MockContainable_AddObserverFunc_Call struct {
	*mock.Call
}

// AddObserverFunc is a helper method to define mock.On call
//   - f func(Containable, chan error)
func (_e *MockContainable_Expecter) AddObserverFunc(f interface{}) *MockContainable_AddObserverFunc_Call {
	return &MockContainable_AddObserverFunc_Call{Call: _e.mock.On("AddObserverFunc", f)}
}

func (_c *MockContainable_AddObserverFunc_Call) Run(run func(f func(Containable, chan error))) *MockContainable_AddObserverFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(Containable, chan error)
		if args[0] != nil {
			arg0 = args[0].(func(Containable, chan error))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_AddObserverFunc_Call) Return() *MockContainable_AddObserverFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContainable_AddObserverFunc_Call) RunAndReturn(run func(f func(Containable, chan error))) *MockContainable_AddObserverFunc_Call {
	_c.Run(run)
	return _c
}

// Dump provides a mock function for the type MockContainable
func (_mock *MockContainable) Dump() {
	_mock.Called()
	return
}

// MockContainable_Dump_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dump'
type MockContainable_Dump_Call struct {
	*mock.Call
}

// Dump is a helper method to define mock.On call
func (_e *MockContainable_Expecter) Dump() *MockContainable_Dump_Call {
	return &MockContainable_Dump_Call{Call: _e.mock.On("Dump")}
}

func (_c *MockContainable_Dump_Call) Run(run func()) *MockContainable_Dump_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainable_Dump_Call) Return() *MockContainable_Dump_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContainable_Dump_Call) RunAndReturn(run func()) *MockContainable_Dump_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockContainable
func (_mock *MockContainable) Get(key string) interface{} {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// MockContainable_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContainable_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) Get(key interface{}) *MockContainable_Get_Call {
	return &MockContainable_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockContainable_Get_Call) Run(run func(key string)) *MockContainable_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_Get_Call) Return(ifaceVal interface{}) *MockContainable_Get_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *MockContainable_Get_Call) RunAndReturn(run func(key string) interface{}) *MockContainable_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBool provides a mock function for the type MockContainable
func (_mock *MockContainable) GetBool(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockContainable_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type MockContainable_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) GetBool(key interface{}) *MockContainable_GetBool_Call {
	return &MockContainable_GetBool_Call{Call: _e.mock.On("GetBool", key)}
}

func (_c *MockContainable_GetBool_Call) Run(run func(key string)) *MockContainable_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_GetBool_Call) Return(b bool) *MockContainable_GetBool_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockContainable_GetBool_Call) RunAndReturn(run func(key string) bool) *MockContainable_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuration provides a mock function for the type MockContainable
func (_mock *MockContainable) GetDuration(key string) time.Duration {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockContainable_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type MockContainable_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) GetDuration(key interface{}) *MockContainable_GetDuration_Call {
	return &MockContainable_GetDuration_Call{Call: _e.mock.On("GetDuration", key)}
}

func (_c *MockContainable_GetDuration_Call) Run(run func(key string)) *MockContainable_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_GetDuration_Call) Return(duration time.Duration) *MockContainable_GetDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockContainable_GetDuration_Call) RunAndReturn(run func(key string) time.Duration) *MockContainable_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloat provides a mock function for the type MockContainable
func (_mock *MockContainable) GetFloat(key string) float64 {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetFloat")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockContainable_GetFloat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloat'
type MockContainable_GetFloat_Call struct {
	*mock.Call
}

// GetFloat is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) GetFloat(key interface{}) *MockContainable_GetFloat_Call {
	return &MockContainable_GetFloat_Call{Call: _e.mock.On("GetFloat", key)}
}

func (_c *MockContainable_GetFloat_Call) Run(run func(key string)) *MockContainable_GetFloat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_GetFloat_Call) Return(f float64) *MockContainable_GetFloat_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockContainable_GetFloat_Call) RunAndReturn(run func(key string) float64) *MockContainable_GetFloat_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function for the type MockContainable
func (_mock *MockContainable) GetInt(key string) int {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockContainable_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type MockContainable_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) GetInt(key interface{}) *MockContainable_GetInt_Call {
	return &MockContainable_GetInt_Call{Call: _e.mock.On("GetInt", key)}
}

func (_c *MockContainable_GetInt_Call) Run(run func(key string)) *MockContainable_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_GetInt_Call) Return(n int) *MockContainable_GetInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockContainable_GetInt_Call) RunAndReturn(run func(key string) int) *MockContainable_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function for the type MockContainable
func (_mock *MockContainable) GetString(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContainable_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockContainable_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) GetString(key interface{}) *MockContainable_GetString_Call {
	return &MockContainable_GetString_Call{Call: _e.mock.On("GetString", key)}
}

func (_c *MockContainable_GetString_Call) Run(run func(key string)) *MockContainable_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_GetString_Call) Return(s string) *MockContainable_GetString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContainable_GetString_Call) RunAndReturn(run func(key string) string) *MockContainable_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// GetTime provides a mock function for the type MockContainable
func (_mock *MockContainable) GetTime(key string) time.Time {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockContainable_GetTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTime'
type MockContainable_GetTime_Call struct {
	*mock.Call
}

// GetTime is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) GetTime(key interface{}) *MockContainable_GetTime_Call {
	return &MockContainable_GetTime_Call{Call: _e.mock.On("GetTime", key)}
}

func (_c *MockContainable_GetTime_Call) Run(run func(key string)) *MockContainable_GetTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_GetTime_Call) Return(time1 time.Time) *MockContainable_GetTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockContainable_GetTime_Call) RunAndReturn(run func(key string) time.Time) *MockContainable_GetTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetViper provides a mock function for the type MockContainable
func (_mock *MockContainable) GetViper() *viper.Viper {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetViper")
	}

	var r0 *viper.Viper
	if returnFunc, ok := ret.Get(0).(func() *viper.Viper); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viper.Viper)
		}
	}
	return r0
}

// MockContainable_GetViper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetViper'
type MockContainable_GetViper_Call struct {
	*mock.Call
}

// GetViper is a helper method to define mock.On call
func (_e *MockContainable_Expecter) GetViper() *MockContainable_GetViper_Call {
	return &MockContainable_GetViper_Call{Call: _e.mock.On("GetViper")}
}

func (_c *MockContainable_GetViper_Call) Run(run func()) *MockContainable_GetViper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainable_GetViper_Call) Return(viper1 *viper.Viper) *MockContainable_GetViper_Call {
	_c.Call.Return(viper1)
	return _c
}

func (_c *MockContainable_GetViper_Call) RunAndReturn(run func() *viper.Viper) *MockContainable_GetViper_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockContainable
func (_mock *MockContainable) Has(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockContainable_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockContainable_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) Has(key interface{}) *MockContainable_Has_Call {
	return &MockContainable_Has_Call{Call: _e.mock.On("Has", key)}
}

func (_c *MockContainable_Has_Call) Run(run func(key string)) *MockContainable_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_Has_Call) Return(b bool) *MockContainable_Has_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockContainable_Has_Call) RunAndReturn(run func(key string) bool) *MockContainable_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Sub provides a mock function for the type MockContainable
func (_mock *MockContainable) Sub(key string) Containable {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Sub")
	}

	var r0 Containable
	if returnFunc, ok := ret.Get(0).(func(string) Containable); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Containable)
		}
	}
	return r0
}

// MockContainable_Sub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sub'
type MockContainable_Sub_Call struct {
	*mock.Call
}

// Sub is a helper method to define mock.On call
//   - key string
func (_e *MockContainable_Expecter) Sub(key interface{}) *MockContainable_Sub_Call {
	return &MockContainable_Sub_Call{Call: _e.mock.On("Sub", key)}
}

func (_c *MockContainable_Sub_Call) Run(run func(key string)) *MockContainable_Sub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainable_Sub_Call) Return(containable Containable) *MockContainable_Sub_Call {
	_c.Call.Return(containable)
	return _c
}

func (_c *MockContainable_Sub_Call) RunAndReturn(run func(key string) Containable) *MockContainable_Sub_Call {
	_c.Call.Return(run)
	return _c
}

// ToJSON provides a mock function for the type MockContainable
func (_mock *MockContainable) ToJSON() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToJSON")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContainable_ToJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToJSON'
type MockContainable_ToJSON_Call struct {
	*mock.Call
}

// ToJSON is a helper method to define mock.On call
func (_e *MockContainable_Expecter) ToJSON() *MockContainable_ToJSON_Call {
	return &MockContainable_ToJSON_Call{Call: _e.mock.On("ToJSON")}
}

func (_c *MockContainable_ToJSON_Call) Run(run func()) *MockContainable_ToJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainable_ToJSON_Call) Return(s string) *MockContainable_ToJSON_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContainable_ToJSON_Call) RunAndReturn(run func() string) *MockContainable_ToJSON_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddedFileReader creates a new instance of MockEmbeddedFileReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddedFileReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddedFileReader {
	mock := &MockEmbeddedFileReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbeddedFileReader is an autogenerated mock type for the EmbeddedFileReader type
type MockEmbeddedFileReader struct {
	mock.Mock
}

type MockEmbeddedFileReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddedFileReader) EXPECT() *MockEmbeddedFileReader_Expecter {
	return &MockEmbeddedFileReader_Expecter{mock: &_m.Mock}
}

// ReadFile provides a mock function for the type MockEmbeddedFileReader
func (_mock *MockEmbeddedFileReader) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddedFileReader_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockEmbeddedFileReader_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *MockEmbeddedFileReader_Expecter) ReadFile(name interface{}) *MockEmbeddedFileReader_ReadFile_Call {
	return &MockEmbeddedFileReader_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockEmbeddedFileReader_ReadFile_Call) Run(run func(name string)) *MockEmbeddedFileReader_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmbeddedFileReader_ReadFile_Call) Return(bytes []byte, err error) *MockEmbeddedFileReader_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockEmbeddedFileReader_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *MockEmbeddedFileReader_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObservable creates a new instance of MockObservable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObservable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObservable {
	mock := &MockObservable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObservable is an autogenerated mock type for the Observable type
type MockObservable struct {
	mock.Mock
}

type MockObservable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObservable) EXPECT() *MockObservable_Expecter {
	return &MockObservable_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockObservable
func (_mock *MockObservable) Run(containable Containable, errCh chan error) {
	_mock.Called(containable, errCh)
	return
}

// MockObservable_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockObservable_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - containable Containable
//   - errCh chan error
func (_e *MockObservable_Expecter) Run(containable interface{}, errCh interface{}) *MockObservable_Run_Call {
	return &MockObservable_Run_Call{Call: _e.mock.On("Run", containable, errCh)}
}

func (_c *MockObservable_Run_Call) Run(run func(containable Containable, errCh chan error)) *MockObservable_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Containable
		if args[0] != nil {
			arg0 = args[0].(Containable)
		}
		var arg1 chan error
		if args[1] != nil {
			arg1 = args[1].(chan error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObservable_Run_Call) Return() *MockObservable_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockObservable_Run_Call) RunAndReturn(run func(containable Containable, errCh chan error)) *MockObservable_Run_Call {
	_c.Run(run)
	return _c
}
