// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function for the type MockBackend
func (_mock *MockBackend) Capabilities() config.Capabilities {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 config.Capabilities
	if returnFunc, ok := ret.Get(0).(func() config.Capabilities); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.Capabilities)
	}
	return r0
}

// MockBackend_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MockBackend_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MockBackend_Expecter) Capabilities() *MockBackend_Capabilities_Call {
	return &MockBackend_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MockBackend_Capabilities_Call) Run(run func()) *MockBackend_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_Capabilities_Call) Return(capabilities config.Capabilities) *MockBackend_Capabilities_Call {
	_c.Call.Return(capabilities)
	return _c
}

func (_c *MockBackend_Capabilities_Call) RunAndReturn(run func() config.Capabilities) *MockBackend_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockBackend
func (_mock *MockBackend) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBackend_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBackend_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBackend_Expecter) ID() *MockBackend_ID_Call {
	return &MockBackend_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBackend_ID_Call) Run(run func()) *MockBackend_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_ID_Call) Return(s string) *MockBackend_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBackend_ID_Call) RunAndReturn(run func() string) *MockBackend_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockBackend
func (_mock *MockBackend) Load(ctx context.Context, below []config.Layer) ([]config.Layer, error) {
	ret := _mock.Called(ctx, below)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []config.Layer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []config.Layer) ([]config.Layer, error)); ok {
		return returnFunc(ctx, below)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []config.Layer) []config.Layer); ok {
		r0 = returnFunc(ctx, below)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Layer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []config.Layer) error); ok {
		r1 = returnFunc(ctx, below)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockBackend_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - below []config.Layer
func (_e *MockBackend_Expecter) Load(ctx interface{}, below interface{}) *MockBackend_Load_Call {
	return &MockBackend_Load_Call{Call: _e.mock.On("Load", ctx, below)}
}

func (_c *MockBackend_Load_Call) Run(run func(ctx context.Context, below []config.Layer)) *MockBackend_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []config.Layer
		if args[1] != nil {
			arg1 = args[1].([]config.Layer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_Load_Call) Return(layers []config.Layer, err error) *MockBackend_Load_Call {
	_c.Call.Return(layers, err)
	return _c
}

func (_c *MockBackend_Load_Call) RunAndReturn(run func(ctx context.Context, below []config.Layer) ([]config.Layer, error)) *MockBackend_Load_Call {
	_c.Call.Return(run)
	return _c
}
