// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockBinder creates a new instance of MockBinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBinder {
	mock := &MockBinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBinder is an autogenerated mock type for the Binder type
type MockBinder struct {
	mock.Mock
}

type MockBinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBinder) EXPECT() *MockBinder_Expecter {
	return &MockBinder_Expecter{mock: &_m.Mock}
}

// AddObserverFunc provides a mock function for the type MockBinder
func (_mock *MockBinder) AddObserverFunc(fn func(config.Observed) error) {
	_mock.Called(fn)
	return
}

// MockBinder_AddObserverFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddObserverFunc'
type MockBinder_AddObserverFunc_Call struct {
	*mock.Call
}

// AddObserverFunc is a helper method to define mock.On call
//   - fn func(config.Observed) error
func (_e *MockBinder_Expecter) AddObserverFunc(fn interface{}) *MockBinder_AddObserverFunc_Call {
	return &MockBinder_AddObserverFunc_Call{Call: _e.mock.On("AddObserverFunc", fn)}
}

func (_c *MockBinder_AddObserverFunc_Call) Run(run func(fn func(config.Observed) error)) *MockBinder_AddObserverFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(config.Observed) error
		if args[0] != nil {
			arg0 = args[0].(func(config.Observed) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBinder_AddObserverFunc_Call) Return() *MockBinder_AddObserverFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBinder_AddObserverFunc_Call) RunAndReturn(run func(fn func(config.Observed) error)) *MockBinder_AddObserverFunc_Call {
	_c.Run(run)
	return _c
}

// View provides a mock function for the type MockBinder
func (_mock *MockBinder) View() *config.View {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 *config.View
	if returnFunc, ok := ret.Get(0).(func() *config.View); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.View)
		}
	}
	return r0
}

// MockBinder_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockBinder_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockBinder_Expecter) View() *MockBinder_View_Call {
	return &MockBinder_View_Call{Call: _e.mock.On("View")}
}

func (_c *MockBinder_View_Call) Run(run func()) *MockBinder_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBinder_View_Call) Return(view *config.View) *MockBinder_View_Call {
	_c.Call.Return(view)
	return _c
}

func (_c *MockBinder_View_Call) RunAndReturn(run func() *config.View) *MockBinder_View_Call {
	_c.Call.Return(run)
	return _c
}
