// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockObservable creates a new instance of MockObservable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObservable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObservable {
	mock := &MockObservable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObservable is an autogenerated mock type for the Observable type
type MockObservable struct {
	mock.Mock
}

type MockObservable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObservable) EXPECT() *MockObservable_Expecter {
	return &MockObservable_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockObservable
func (_mock *MockObservable) Run(cfg config.Observed) error {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(config.Observed) error); ok {
		r0 = returnFunc(cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObservable_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockObservable_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - cfg config.Observed
func (_e *MockObservable_Expecter) Run(cfg interface{}) *MockObservable_Run_Call {
	return &MockObservable_Run_Call{Call: _e.mock.On("Run", cfg)}
}

func (_c *MockObservable_Run_Call) Run(run func(cfg config.Observed)) *MockObservable_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Observed
		if args[0] != nil {
			arg0 = args[0].(config.Observed)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObservable_Run_Call) Return(err error) *MockObservable_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObservable_Run_Call) RunAndReturn(run func(cfg config.Observed) error) *MockObservable_Run_Call {
	_c.Call.Return(run)
	return _c
}
