// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockObserved creates a new instance of MockObserved. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObserved(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObserved {
	mock := &MockObserved{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObserved is an autogenerated mock type for the Observed type
type MockObserved struct {
	mock.Mock
}

type MockObserved_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObserved) EXPECT() *MockObserved_Expecter {
	return &MockObserved_Expecter{mock: &_m.Mock}
}

// Explain provides a mock function for the type MockObserved
func (_mock *MockObserved) Explain(path string) string {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Explain")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockObserved_Explain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Explain'
type MockObserved_Explain_Call struct {
	*mock.Call
}

// Explain is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) Explain(path interface{}) *MockObserved_Explain_Call {
	return &MockObserved_Explain_Call{Call: _e.mock.On("Explain", path)}
}

func (_c *MockObserved_Explain_Call) Run(run func(path string)) *MockObserved_Explain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_Explain_Call) Return(s string) *MockObserved_Explain_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockObserved_Explain_Call) RunAndReturn(run func(path string) string) *MockObserved_Explain_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockObserved
func (_mock *MockObserved) Get(path string) any {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockObserved_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockObserved_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) Get(path interface{}) *MockObserved_Get_Call {
	return &MockObserved_Get_Call{Call: _e.mock.On("Get", path)}
}

func (_c *MockObserved_Get_Call) Run(run func(path string)) *MockObserved_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_Get_Call) Return(v any) *MockObserved_Get_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockObserved_Get_Call) RunAndReturn(run func(path string) any) *MockObserved_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBool provides a mock function for the type MockObserved
func (_mock *MockObserved) GetBool(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockObserved_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type MockObserved_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) GetBool(path interface{}) *MockObserved_GetBool_Call {
	return &MockObserved_GetBool_Call{Call: _e.mock.On("GetBool", path)}
}

func (_c *MockObserved_GetBool_Call) Run(run func(path string)) *MockObserved_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_GetBool_Call) Return(b bool) *MockObserved_GetBool_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockObserved_GetBool_Call) RunAndReturn(run func(path string) bool) *MockObserved_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuration provides a mock function for the type MockObserved
func (_mock *MockObserved) GetDuration(path string) time.Duration {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockObserved_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type MockObserved_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) GetDuration(path interface{}) *MockObserved_GetDuration_Call {
	return &MockObserved_GetDuration_Call{Call: _e.mock.On("GetDuration", path)}
}

func (_c *MockObserved_GetDuration_Call) Run(run func(path string)) *MockObserved_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_GetDuration_Call) Return(duration time.Duration) *MockObserved_GetDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockObserved_GetDuration_Call) RunAndReturn(run func(path string) time.Duration) *MockObserved_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloat provides a mock function for the type MockObserved
func (_mock *MockObserved) GetFloat(path string) float64 {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetFloat")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockObserved_GetFloat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloat'
type MockObserved_GetFloat_Call struct {
	*mock.Call
}

// GetFloat is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) GetFloat(path interface{}) *MockObserved_GetFloat_Call {
	return &MockObserved_GetFloat_Call{Call: _e.mock.On("GetFloat", path)}
}

func (_c *MockObserved_GetFloat_Call) Run(run func(path string)) *MockObserved_GetFloat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_GetFloat_Call) Return(f float64) *MockObserved_GetFloat_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockObserved_GetFloat_Call) RunAndReturn(run func(path string) float64) *MockObserved_GetFloat_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function for the type MockObserved
func (_mock *MockObserved) GetInt(path string) int {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockObserved_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type MockObserved_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) GetInt(path interface{}) *MockObserved_GetInt_Call {
	return &MockObserved_GetInt_Call{Call: _e.mock.On("GetInt", path)}
}

func (_c *MockObserved_GetInt_Call) Run(run func(path string)) *MockObserved_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_GetInt_Call) Return(n int) *MockObserved_GetInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockObserved_GetInt_Call) RunAndReturn(run func(path string) int) *MockObserved_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function for the type MockObserved
func (_mock *MockObserved) GetString(path string) string {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockObserved_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockObserved_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) GetString(path interface{}) *MockObserved_GetString_Call {
	return &MockObserved_GetString_Call{Call: _e.mock.On("GetString", path)}
}

func (_c *MockObserved_GetString_Call) Run(run func(path string)) *MockObserved_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_GetString_Call) Return(s string) *MockObserved_GetString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockObserved_GetString_Call) RunAndReturn(run func(path string) string) *MockObserved_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringSlice provides a mock function for the type MockObserved
func (_mock *MockObserved) GetStringSlice(path string) []string {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetStringSlice")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockObserved_GetStringSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringSlice'
type MockObserved_GetStringSlice_Call struct {
	*mock.Call
}

// GetStringSlice is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) GetStringSlice(path interface{}) *MockObserved_GetStringSlice_Call {
	return &MockObserved_GetStringSlice_Call{Call: _e.mock.On("GetStringSlice", path)}
}

func (_c *MockObserved_GetStringSlice_Call) Run(run func(path string)) *MockObserved_GetStringSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_GetStringSlice_Call) Return(strings []string) *MockObserved_GetStringSlice_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockObserved_GetStringSlice_Call) RunAndReturn(run func(path string) []string) *MockObserved_GetStringSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetTime provides a mock function for the type MockObserved
func (_mock *MockObserved) GetTime(path string) time.Time {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockObserved_GetTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTime'
type MockObserved_GetTime_Call struct {
	*mock.Call
}

// GetTime is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) GetTime(path interface{}) *MockObserved_GetTime_Call {
	return &MockObserved_GetTime_Call{Call: _e.mock.On("GetTime", path)}
}

func (_c *MockObserved_GetTime_Call) Run(run func(path string)) *MockObserved_GetTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_GetTime_Call) Return(time1 time.Time) *MockObserved_GetTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockObserved_GetTime_Call) RunAndReturn(run func(path string) time.Time) *MockObserved_GetTime_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockObserved
func (_mock *MockObserved) Has(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockObserved_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockObserved_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) Has(path interface{}) *MockObserved_Has_Call {
	return &MockObserved_Has_Call{Call: _e.mock.On("Has", path)}
}

func (_c *MockObserved_Has_Call) Run(run func(path string)) *MockObserved_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_Has_Call) Return(b bool) *MockObserved_Has_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockObserved_Has_Call) RunAndReturn(run func(path string) bool) *MockObserved_Has_Call {
	_c.Call.Return(run)
	return _c
}

// IsSet provides a mock function for the type MockObserved
func (_mock *MockObserved) IsSet(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsSet")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockObserved_IsSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSet'
type MockObserved_IsSet_Call struct {
	*mock.Call
}

// IsSet is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) IsSet(path interface{}) *MockObserved_IsSet_Call {
	return &MockObserved_IsSet_Call{Call: _e.mock.On("IsSet", path)}
}

func (_c *MockObserved_IsSet_Call) Run(run func(path string)) *MockObserved_IsSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_IsSet_Call) Return(b bool) *MockObserved_IsSet_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockObserved_IsSet_Call) RunAndReturn(run func(path string) bool) *MockObserved_IsSet_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type MockObserved
func (_mock *MockObserved) Keys() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockObserved_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockObserved_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockObserved_Expecter) Keys() *MockObserved_Keys_Call {
	return &MockObserved_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockObserved_Keys_Call) Run(run func()) *MockObserved_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObserved_Keys_Call) Return(strings []string) *MockObserved_Keys_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockObserved_Keys_Call) RunAndReturn(run func() []string) *MockObserved_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Origin provides a mock function for the type MockObserved
func (_mock *MockObserved) Origin(path string) (config.Source, bool) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Origin")
	}

	var r0 config.Source
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (config.Source, bool)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) config.Source); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(config.Source)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockObserved_Origin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Origin'
type MockObserved_Origin_Call struct {
	*mock.Call
}

// Origin is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) Origin(path interface{}) *MockObserved_Origin_Call {
	return &MockObserved_Origin_Call{Call: _e.mock.On("Origin", path)}
}

func (_c *MockObserved_Origin_Call) Run(run func(path string)) *MockObserved_Origin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_Origin_Call) Return(source config.Source, b bool) *MockObserved_Origin_Call {
	_c.Call.Return(source, b)
	return _c
}

func (_c *MockObserved_Origin_Call) RunAndReturn(run func(path string) (config.Source, bool)) *MockObserved_Origin_Call {
	_c.Call.Return(run)
	return _c
}

// SectionExists provides a mock function for the type MockObserved
func (_mock *MockObserved) SectionExists(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for SectionExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockObserved_SectionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SectionExists'
type MockObserved_SectionExists_Call struct {
	*mock.Call
}

// SectionExists is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) SectionExists(path interface{}) *MockObserved_SectionExists_Call {
	return &MockObserved_SectionExists_Call{Call: _e.mock.On("SectionExists", path)}
}

func (_c *MockObserved_SectionExists_Call) Run(run func(path string)) *MockObserved_SectionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_SectionExists_Call) Return(b bool) *MockObserved_SectionExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockObserved_SectionExists_Call) RunAndReturn(run func(path string) bool) *MockObserved_SectionExists_Call {
	_c.Call.Return(run)
	return _c
}

// Shadowed provides a mock function for the type MockObserved
func (_mock *MockObserved) Shadowed(path string) []config.Source {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Shadowed")
	}

	var r0 []config.Source
	if returnFunc, ok := ret.Get(0).(func(string) []config.Source); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Source)
		}
	}
	return r0
}

// MockObserved_Shadowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shadowed'
type MockObserved_Shadowed_Call struct {
	*mock.Call
}

// Shadowed is a helper method to define mock.On call
//   - path string
func (_e *MockObserved_Expecter) Shadowed(path interface{}) *MockObserved_Shadowed_Call {
	return &MockObserved_Shadowed_Call{Call: _e.mock.On("Shadowed", path)}
}

func (_c *MockObserved_Shadowed_Call) Run(run func(path string)) *MockObserved_Shadowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_Shadowed_Call) Return(sources []config.Source) *MockObserved_Shadowed_Call {
	_c.Call.Return(sources)
	return _c
}

func (_c *MockObserved_Shadowed_Call) RunAndReturn(run func(path string) []config.Source) *MockObserved_Shadowed_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type MockObserved
func (_mock *MockObserved) Snapshot() *config.Snapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 *config.Snapshot
	if returnFunc, ok := ret.Get(0).(func() *config.Snapshot); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Snapshot)
		}
	}
	return r0
}

// MockObserved_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockObserved_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockObserved_Expecter) Snapshot() *MockObserved_Snapshot_Call {
	return &MockObserved_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockObserved_Snapshot_Call) Run(run func()) *MockObserved_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObserved_Snapshot_Call) Return(snapshot *config.Snapshot) *MockObserved_Snapshot_Call {
	_c.Call.Return(snapshot)
	return _c
}

func (_c *MockObserved_Snapshot_Call) RunAndReturn(run func() *config.Snapshot) *MockObserved_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Sub provides a mock function for the type MockObserved
func (_mock *MockObserved) Sub(key string) *config.View {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Sub")
	}

	var r0 *config.View
	if returnFunc, ok := ret.Get(0).(func(string) *config.View); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.View)
		}
	}
	return r0
}

// MockObserved_Sub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sub'
type MockObserved_Sub_Call struct {
	*mock.Call
}

// Sub is a helper method to define mock.On call
//   - key string
func (_e *MockObserved_Expecter) Sub(key interface{}) *MockObserved_Sub_Call {
	return &MockObserved_Sub_Call{Call: _e.mock.On("Sub", key)}
}

func (_c *MockObserved_Sub_Call) Run(run func(key string)) *MockObserved_Sub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_Sub_Call) Return(view *config.View) *MockObserved_Sub_Call {
	_c.Call.Return(view)
	return _c
}

func (_c *MockObserved_Sub_Call) RunAndReturn(run func(key string) *config.View) *MockObserved_Sub_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type MockObserved
func (_mock *MockObserved) Unmarshal(target any) error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObserved_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockObserved_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - target any
func (_e *MockObserved_Expecter) Unmarshal(target interface{}) *MockObserved_Unmarshal_Call {
	return &MockObserved_Unmarshal_Call{Call: _e.mock.On("Unmarshal", target)}
}

func (_c *MockObserved_Unmarshal_Call) Run(run func(target any)) *MockObserved_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserved_Unmarshal_Call) Return(err error) *MockObserved_Unmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObserved_Unmarshal_Call) RunAndReturn(run func(target any) error) *MockObserved_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalKey provides a mock function for the type MockObserved
func (_mock *MockObserved) UnmarshalKey(path string, target any) error {
	ret := _mock.Called(path, target)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(path, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObserved_UnmarshalKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalKey'
type MockObserved_UnmarshalKey_Call struct {
	*mock.Call
}

// UnmarshalKey is a helper method to define mock.On call
//   - path string
//   - target any
func (_e *MockObserved_Expecter) UnmarshalKey(path interface{}, target interface{}) *MockObserved_UnmarshalKey_Call {
	return &MockObserved_UnmarshalKey_Call{Call: _e.mock.On("UnmarshalKey", path, target)}
}

func (_c *MockObserved_UnmarshalKey_Call) Run(run func(path string, target any)) *MockObserved_UnmarshalKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObserved_UnmarshalKey_Call) Return(err error) *MockObserved_UnmarshalKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObserved_UnmarshalKey_Call) RunAndReturn(run func(path string, target any) error) *MockObserved_UnmarshalKey_Call {
	_c.Call.Return(run)
	return _c
}
