// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// Explain provides a mock function for the type MockReader
func (_mock *MockReader) Explain(path string) string {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Explain")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReader_Explain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Explain'
type MockReader_Explain_Call struct {
	*mock.Call
}

// Explain is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) Explain(path interface{}) *MockReader_Explain_Call {
	return &MockReader_Explain_Call{Call: _e.mock.On("Explain", path)}
}

func (_c *MockReader_Explain_Call) Run(run func(path string)) *MockReader_Explain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Explain_Call) Return(s string) *MockReader_Explain_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReader_Explain_Call) RunAndReturn(run func(path string) string) *MockReader_Explain_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockReader
func (_mock *MockReader) Get(path string) any {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) Get(path interface{}) *MockReader_Get_Call {
	return &MockReader_Get_Call{Call: _e.mock.On("Get", path)}
}

func (_c *MockReader_Get_Call) Run(run func(path string)) *MockReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Get_Call) Return(v any) *MockReader_Get_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockReader_Get_Call) RunAndReturn(run func(path string) any) *MockReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBool provides a mock function for the type MockReader
func (_mock *MockReader) GetBool(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockReader_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type MockReader_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) GetBool(path interface{}) *MockReader_GetBool_Call {
	return &MockReader_GetBool_Call{Call: _e.mock.On("GetBool", path)}
}

func (_c *MockReader_GetBool_Call) Run(run func(path string)) *MockReader_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetBool_Call) Return(b bool) *MockReader_GetBool_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockReader_GetBool_Call) RunAndReturn(run func(path string) bool) *MockReader_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuration provides a mock function for the type MockReader
func (_mock *MockReader) GetDuration(path string) time.Duration {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockReader_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type MockReader_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) GetDuration(path interface{}) *MockReader_GetDuration_Call {
	return &MockReader_GetDuration_Call{Call: _e.mock.On("GetDuration", path)}
}

func (_c *MockReader_GetDuration_Call) Run(run func(path string)) *MockReader_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetDuration_Call) Return(duration time.Duration) *MockReader_GetDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockReader_GetDuration_Call) RunAndReturn(run func(path string) time.Duration) *MockReader_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloat provides a mock function for the type MockReader
func (_mock *MockReader) GetFloat(path string) float64 {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetFloat")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockReader_GetFloat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloat'
type MockReader_GetFloat_Call struct {
	*mock.Call
}

// GetFloat is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) GetFloat(path interface{}) *MockReader_GetFloat_Call {
	return &MockReader_GetFloat_Call{Call: _e.mock.On("GetFloat", path)}
}

func (_c *MockReader_GetFloat_Call) Run(run func(path string)) *MockReader_GetFloat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetFloat_Call) Return(f float64) *MockReader_GetFloat_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockReader_GetFloat_Call) RunAndReturn(run func(path string) float64) *MockReader_GetFloat_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function for the type MockReader
func (_mock *MockReader) GetInt(path string) int {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockReader_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type MockReader_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) GetInt(path interface{}) *MockReader_GetInt_Call {
	return &MockReader_GetInt_Call{Call: _e.mock.On("GetInt", path)}
}

func (_c *MockReader_GetInt_Call) Run(run func(path string)) *MockReader_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetInt_Call) Return(n int) *MockReader_GetInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockReader_GetInt_Call) RunAndReturn(run func(path string) int) *MockReader_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function for the type MockReader
func (_mock *MockReader) GetString(path string) string {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReader_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockReader_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) GetString(path interface{}) *MockReader_GetString_Call {
	return &MockReader_GetString_Call{Call: _e.mock.On("GetString", path)}
}

func (_c *MockReader_GetString_Call) Run(run func(path string)) *MockReader_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetString_Call) Return(s string) *MockReader_GetString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReader_GetString_Call) RunAndReturn(run func(path string) string) *MockReader_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringSlice provides a mock function for the type MockReader
func (_mock *MockReader) GetStringSlice(path string) []string {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetStringSlice")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockReader_GetStringSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringSlice'
type MockReader_GetStringSlice_Call struct {
	*mock.Call
}

// GetStringSlice is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) GetStringSlice(path interface{}) *MockReader_GetStringSlice_Call {
	return &MockReader_GetStringSlice_Call{Call: _e.mock.On("GetStringSlice", path)}
}

func (_c *MockReader_GetStringSlice_Call) Run(run func(path string)) *MockReader_GetStringSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetStringSlice_Call) Return(strings []string) *MockReader_GetStringSlice_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockReader_GetStringSlice_Call) RunAndReturn(run func(path string) []string) *MockReader_GetStringSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetTime provides a mock function for the type MockReader
func (_mock *MockReader) GetTime(path string) time.Time {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockReader_GetTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTime'
type MockReader_GetTime_Call struct {
	*mock.Call
}

// GetTime is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) GetTime(path interface{}) *MockReader_GetTime_Call {
	return &MockReader_GetTime_Call{Call: _e.mock.On("GetTime", path)}
}

func (_c *MockReader_GetTime_Call) Run(run func(path string)) *MockReader_GetTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetTime_Call) Return(time1 time.Time) *MockReader_GetTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockReader_GetTime_Call) RunAndReturn(run func(path string) time.Time) *MockReader_GetTime_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockReader
func (_mock *MockReader) Has(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockReader_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockReader_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) Has(path interface{}) *MockReader_Has_Call {
	return &MockReader_Has_Call{Call: _e.mock.On("Has", path)}
}

func (_c *MockReader_Has_Call) Run(run func(path string)) *MockReader_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Has_Call) Return(b bool) *MockReader_Has_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockReader_Has_Call) RunAndReturn(run func(path string) bool) *MockReader_Has_Call {
	_c.Call.Return(run)
	return _c
}

// IsSet provides a mock function for the type MockReader
func (_mock *MockReader) IsSet(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsSet")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockReader_IsSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSet'
type MockReader_IsSet_Call struct {
	*mock.Call
}

// IsSet is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) IsSet(path interface{}) *MockReader_IsSet_Call {
	return &MockReader_IsSet_Call{Call: _e.mock.On("IsSet", path)}
}

func (_c *MockReader_IsSet_Call) Run(run func(path string)) *MockReader_IsSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_IsSet_Call) Return(b bool) *MockReader_IsSet_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockReader_IsSet_Call) RunAndReturn(run func(path string) bool) *MockReader_IsSet_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type MockReader
func (_mock *MockReader) Keys() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockReader_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockReader_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockReader_Expecter) Keys() *MockReader_Keys_Call {
	return &MockReader_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockReader_Keys_Call) Run(run func()) *MockReader_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReader_Keys_Call) Return(strings []string) *MockReader_Keys_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockReader_Keys_Call) RunAndReturn(run func() []string) *MockReader_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Origin provides a mock function for the type MockReader
func (_mock *MockReader) Origin(path string) (config.Source, bool) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Origin")
	}

	var r0 config.Source
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (config.Source, bool)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) config.Source); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(config.Source)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockReader_Origin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Origin'
type MockReader_Origin_Call struct {
	*mock.Call
}

// Origin is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) Origin(path interface{}) *MockReader_Origin_Call {
	return &MockReader_Origin_Call{Call: _e.mock.On("Origin", path)}
}

func (_c *MockReader_Origin_Call) Run(run func(path string)) *MockReader_Origin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Origin_Call) Return(source config.Source, b bool) *MockReader_Origin_Call {
	_c.Call.Return(source, b)
	return _c
}

func (_c *MockReader_Origin_Call) RunAndReturn(run func(path string) (config.Source, bool)) *MockReader_Origin_Call {
	_c.Call.Return(run)
	return _c
}

// SectionExists provides a mock function for the type MockReader
func (_mock *MockReader) SectionExists(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for SectionExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockReader_SectionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SectionExists'
type MockReader_SectionExists_Call struct {
	*mock.Call
}

// SectionExists is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) SectionExists(path interface{}) *MockReader_SectionExists_Call {
	return &MockReader_SectionExists_Call{Call: _e.mock.On("SectionExists", path)}
}

func (_c *MockReader_SectionExists_Call) Run(run func(path string)) *MockReader_SectionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_SectionExists_Call) Return(b bool) *MockReader_SectionExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockReader_SectionExists_Call) RunAndReturn(run func(path string) bool) *MockReader_SectionExists_Call {
	_c.Call.Return(run)
	return _c
}

// Shadowed provides a mock function for the type MockReader
func (_mock *MockReader) Shadowed(path string) []config.Source {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Shadowed")
	}

	var r0 []config.Source
	if returnFunc, ok := ret.Get(0).(func(string) []config.Source); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Source)
		}
	}
	return r0
}

// MockReader_Shadowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shadowed'
type MockReader_Shadowed_Call struct {
	*mock.Call
}

// Shadowed is a helper method to define mock.On call
//   - path string
func (_e *MockReader_Expecter) Shadowed(path interface{}) *MockReader_Shadowed_Call {
	return &MockReader_Shadowed_Call{Call: _e.mock.On("Shadowed", path)}
}

func (_c *MockReader_Shadowed_Call) Run(run func(path string)) *MockReader_Shadowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Shadowed_Call) Return(sources []config.Source) *MockReader_Shadowed_Call {
	_c.Call.Return(sources)
	return _c
}

func (_c *MockReader_Shadowed_Call) RunAndReturn(run func(path string) []config.Source) *MockReader_Shadowed_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type MockReader
func (_mock *MockReader) Unmarshal(target any) error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReader_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockReader_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - target any
func (_e *MockReader_Expecter) Unmarshal(target interface{}) *MockReader_Unmarshal_Call {
	return &MockReader_Unmarshal_Call{Call: _e.mock.On("Unmarshal", target)}
}

func (_c *MockReader_Unmarshal_Call) Run(run func(target any)) *MockReader_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Unmarshal_Call) Return(err error) *MockReader_Unmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReader_Unmarshal_Call) RunAndReturn(run func(target any) error) *MockReader_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalKey provides a mock function for the type MockReader
func (_mock *MockReader) UnmarshalKey(path string, target any) error {
	ret := _mock.Called(path, target)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(path, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReader_UnmarshalKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalKey'
type MockReader_UnmarshalKey_Call struct {
	*mock.Call
}

// UnmarshalKey is a helper method to define mock.On call
//   - path string
//   - target any
func (_e *MockReader_Expecter) UnmarshalKey(path interface{}, target interface{}) *MockReader_UnmarshalKey_Call {
	return &MockReader_UnmarshalKey_Call{Call: _e.mock.On("UnmarshalKey", path, target)}
}

func (_c *MockReader_UnmarshalKey_Call) Run(run func(path string, target any)) *MockReader_UnmarshalKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReader_UnmarshalKey_Call) Return(err error) *MockReader_UnmarshalKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReader_UnmarshalKey_Call) RunAndReturn(run func(path string, target any) error) *MockReader_UnmarshalKey_Call {
	_c.Call.Return(run)
	return _c
}
