// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockWatchableBackend creates a new instance of MockWatchableBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchableBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchableBackend {
	mock := &MockWatchableBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchableBackend is an autogenerated mock type for the WatchableBackend type
type MockWatchableBackend struct {
	mock.Mock
}

type MockWatchableBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchableBackend) EXPECT() *MockWatchableBackend_Expecter {
	return &MockWatchableBackend_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function for the type MockWatchableBackend
func (_mock *MockWatchableBackend) Capabilities() config.Capabilities {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 config.Capabilities
	if returnFunc, ok := ret.Get(0).(func() config.Capabilities); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.Capabilities)
	}
	return r0
}

// MockWatchableBackend_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MockWatchableBackend_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MockWatchableBackend_Expecter) Capabilities() *MockWatchableBackend_Capabilities_Call {
	return &MockWatchableBackend_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MockWatchableBackend_Capabilities_Call) Run(run func()) *MockWatchableBackend_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatchableBackend_Capabilities_Call) Return(capabilities config.Capabilities) *MockWatchableBackend_Capabilities_Call {
	_c.Call.Return(capabilities)
	return _c
}

func (_c *MockWatchableBackend_Capabilities_Call) RunAndReturn(run func() config.Capabilities) *MockWatchableBackend_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockWatchableBackend
func (_mock *MockWatchableBackend) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWatchableBackend_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockWatchableBackend_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockWatchableBackend_Expecter) ID() *MockWatchableBackend_ID_Call {
	return &MockWatchableBackend_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockWatchableBackend_ID_Call) Run(run func()) *MockWatchableBackend_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatchableBackend_ID_Call) Return(s string) *MockWatchableBackend_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWatchableBackend_ID_Call) RunAndReturn(run func() string) *MockWatchableBackend_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockWatchableBackend
func (_mock *MockWatchableBackend) Load(ctx context.Context, below []config.Layer) ([]config.Layer, error) {
	ret := _mock.Called(ctx, below)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []config.Layer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []config.Layer) ([]config.Layer, error)); ok {
		return returnFunc(ctx, below)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []config.Layer) []config.Layer); ok {
		r0 = returnFunc(ctx, below)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Layer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []config.Layer) error); ok {
		r1 = returnFunc(ctx, below)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWatchableBackend_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockWatchableBackend_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - below []config.Layer
func (_e *MockWatchableBackend_Expecter) Load(ctx interface{}, below interface{}) *MockWatchableBackend_Load_Call {
	return &MockWatchableBackend_Load_Call{Call: _e.mock.On("Load", ctx, below)}
}

func (_c *MockWatchableBackend_Load_Call) Run(run func(ctx context.Context, below []config.Layer)) *MockWatchableBackend_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []config.Layer
		if args[1] != nil {
			arg1 = args[1].([]config.Layer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWatchableBackend_Load_Call) Return(layers []config.Layer, err error) *MockWatchableBackend_Load_Call {
	_c.Call.Return(layers, err)
	return _c
}

func (_c *MockWatchableBackend_Load_Call) RunAndReturn(run func(ctx context.Context, below []config.Layer) ([]config.Layer, error)) *MockWatchableBackend_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockWatchableBackend
func (_mock *MockWatchableBackend) Watch(ctx context.Context, interval time.Duration, onChange func()) (func(), error) {
	ret := _mock.Called(ctx, interval, onChange)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 func()
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, func()) (func(), error)); ok {
		return returnFunc(ctx, interval, onChange)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, func()) func()); ok {
		r0 = returnFunc(ctx, interval, onChange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, func()) error); ok {
		r1 = returnFunc(ctx, interval, onChange)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWatchableBackend_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockWatchableBackend_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - interval time.Duration
//   - onChange func()
func (_e *MockWatchableBackend_Expecter) Watch(ctx interface{}, interval interface{}, onChange interface{}) *MockWatchableBackend_Watch_Call {
	return &MockWatchableBackend_Watch_Call{Call: _e.mock.On("Watch", ctx, interval, onChange)}
}

func (_c *MockWatchableBackend_Watch_Call) Run(run func(ctx context.Context, interval time.Duration, onChange func())) *MockWatchableBackend_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 func()
		if args[2] != nil {
			arg2 = args[2].(func())
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWatchableBackend_Watch_Call) Return(stop func(), err error) *MockWatchableBackend_Watch_Call {
	_c.Call.Return(stop, err)
	return _c
}

func (_c *MockWatchableBackend_Watch_Call) RunAndReturn(run func(ctx context.Context, interval time.Duration, onChange func()) (func(), error)) *MockWatchableBackend_Watch_Call {
	_c.Call.Return(run)
	return _c
}
