// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/config"
)

// NewMockWritableBackend creates a new instance of MockWritableBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWritableBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWritableBackend {
	mock := &MockWritableBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWritableBackend is an autogenerated mock type for the WritableBackend type
type MockWritableBackend struct {
	mock.Mock
}

type MockWritableBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWritableBackend) EXPECT() *MockWritableBackend_Expecter {
	return &MockWritableBackend_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function for the type MockWritableBackend
func (_mock *MockWritableBackend) Capabilities() config.Capabilities {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 config.Capabilities
	if returnFunc, ok := ret.Get(0).(func() config.Capabilities); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.Capabilities)
	}
	return r0
}

// MockWritableBackend_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MockWritableBackend_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MockWritableBackend_Expecter) Capabilities() *MockWritableBackend_Capabilities_Call {
	return &MockWritableBackend_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MockWritableBackend_Capabilities_Call) Run(run func()) *MockWritableBackend_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWritableBackend_Capabilities_Call) Return(capabilities config.Capabilities) *MockWritableBackend_Capabilities_Call {
	_c.Call.Return(capabilities)
	return _c
}

func (_c *MockWritableBackend_Capabilities_Call) RunAndReturn(run func() config.Capabilities) *MockWritableBackend_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockWritableBackend
func (_mock *MockWritableBackend) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWritableBackend_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockWritableBackend_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockWritableBackend_Expecter) ID() *MockWritableBackend_ID_Call {
	return &MockWritableBackend_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockWritableBackend_ID_Call) Run(run func()) *MockWritableBackend_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWritableBackend_ID_Call) Return(s string) *MockWritableBackend_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWritableBackend_ID_Call) RunAndReturn(run func() string) *MockWritableBackend_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockWritableBackend
func (_mock *MockWritableBackend) Load(ctx context.Context, below []config.Layer) ([]config.Layer, error) {
	ret := _mock.Called(ctx, below)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []config.Layer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []config.Layer) ([]config.Layer, error)); ok {
		return returnFunc(ctx, below)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []config.Layer) []config.Layer); ok {
		r0 = returnFunc(ctx, below)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Layer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []config.Layer) error); ok {
		r1 = returnFunc(ctx, below)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWritableBackend_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockWritableBackend_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - below []config.Layer
func (_e *MockWritableBackend_Expecter) Load(ctx interface{}, below interface{}) *MockWritableBackend_Load_Call {
	return &MockWritableBackend_Load_Call{Call: _e.mock.On("Load", ctx, below)}
}

func (_c *MockWritableBackend_Load_Call) Run(run func(ctx context.Context, below []config.Layer)) *MockWritableBackend_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []config.Layer
		if args[1] != nil {
			arg1 = args[1].([]config.Layer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWritableBackend_Load_Call) Return(layers []config.Layer, err error) *MockWritableBackend_Load_Call {
	_c.Call.Return(layers, err)
	return _c
}

func (_c *MockWritableBackend_Load_Call) RunAndReturn(run func(ctx context.Context, below []config.Layer) ([]config.Layer, error)) *MockWritableBackend_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type MockWritableBackend
func (_mock *MockWritableBackend) Prepare(ctx context.Context, edits []config.Edit) (config.Pending, error) {
	ret := _mock.Called(ctx, edits)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 config.Pending
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []config.Edit) (config.Pending, error)); ok {
		return returnFunc(ctx, edits)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []config.Edit) config.Pending); ok {
		r0 = returnFunc(ctx, edits)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Pending)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []config.Edit) error); ok {
		r1 = returnFunc(ctx, edits)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWritableBackend_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockWritableBackend_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
//   - edits []config.Edit
func (_e *MockWritableBackend_Expecter) Prepare(ctx interface{}, edits interface{}) *MockWritableBackend_Prepare_Call {
	return &MockWritableBackend_Prepare_Call{Call: _e.mock.On("Prepare", ctx, edits)}
}

func (_c *MockWritableBackend_Prepare_Call) Run(run func(ctx context.Context, edits []config.Edit)) *MockWritableBackend_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []config.Edit
		if args[1] != nil {
			arg1 = args[1].([]config.Edit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWritableBackend_Prepare_Call) Return(pending config.Pending, err error) *MockWritableBackend_Prepare_Call {
	_c.Call.Return(pending, err)
	return _c
}

func (_c *MockWritableBackend_Prepare_Call) RunAndReturn(run func(ctx context.Context, edits []config.Edit) (config.Pending, error)) *MockWritableBackend_Prepare_Call {
	_c.Call.Return(run)
	return _c
}
